name: CI-CD Pipeline

on:
  push:
    branches: ["master"]

env:
  IMAGE_NAME: githubaction-project
  REGISTRY: docker.io
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:

# ---------------- BUILD ----------------
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t $DOCKER_USER/$IMAGE_NAME:latest .

    - name: Push Image
      run: docker push $DOCKER_USER/$IMAGE_NAME:latest


# ---------------- DEPLOY ----------------
  deploy:
    runs-on: [self-hosted, k8s-deploy]
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Setup kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Verify Cluster Access
      run: kubectl get nodes

    - name: Update Deployment Image
      run: |
        kubectl set image deployment/app-deployment app-container=$DOCKER_USER/$IMAGE_NAME:latest

    - name: Apply YAML (if first time)
      run: kubectl apply -f k8s/deployment.yaml

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get svc
